apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: aidandang/ticketing-auth
      context: auth
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: aidandang/ticketing-client
      context: client
      sync:
        manual:
          - src: '**/*.js'
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: aidandang/ticketing-tickets
      context: tickets
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: aidandang/ticketing-orders
      context: orders
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: aidandang/ticketing-expiration
      context: expiration
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: aidandang/ticketing-payments
      context: payments
      sync:
        manual:
          - src: src/**/*.ts
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
    - ./infra/k8s-dev/*
deploy:
  kubectl: {}
